version: "3"
services:
  vscode:
    image: serialt/vscode:v4.12.0
    container_name: vscode
    hostname: vscode
    restart: always
    environment:
      CS_HASHED_PASSWORD: '$argon2i$v=19$m=4096,t=3,p=1$ndQZbJFPeeuSm8wbq8k8Mg$W1C5cXmuSoQD8f/vJQyujytoZEoG5DdJN1c8LUH9Ldo'
      # CS_SERVER_PORT: '0.0.0.0:80'
      # CS_DISABLE_UPDATE_CHECK: false
      # CS_DISABLE_FILE_DOWNLOADS=false
      # CS_CONFIG: "~/.config/code-server/config.yaml"
      # CS_USER_DATA_DIR: "~/.local/share/code-server"
      # CS_EXTENSIONS_DIR: ""
      # CS_APP_NAME: ""
      # CS_WELCOME_TEXT: ""
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/usr/bin/docker-compose:/usr/bin/docker-compose"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${HOME}/.ssh:${HOME}/.ssh"
      - "${HOME}/github:/root/github"
    ports:
      - "127.0.0.1:8080:80"