name: sync

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  schedule:
    - cron: "30 5 * * 1"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  IMAGE_NAME: vscode #这是您的镜像名
  APP: vscode
  APP_REPO: https://github.com/coder/code-server.git

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: get tag
        id: get_tag
        run: |
          ADD_TAG=""
          tags="$(git ls-remote --tags $APP_REPO | grep 'v[1-9]\.[0-9]*\.[0-9]*$' | awk -F'tags/' '{print $2}' | sort -t. -k1,1n -k2,2n -k3,3n)"
          set -x
          new_tags="$(printf "%s" "$tags"| sed -n '{/\.0$/{g;p}};h' | tail -3) $(printf "%s" "$tags" | tail -1)"
          echo "::debug::[Tags] $new_tags"
          for t in $new_tags; do
            echo "[check] $t"
            b=$(echo "${APP_VERSION}" | grep -w ${t} | wc -l)
            if [[ $b == 0 ]]; then
              echo "::group::[Build] $t"
              
              echo "::debug::[Push file]"
              echo "${t}" >> version.txt
              fix_tag=$(echo v3.10.2 | awk -F 'v' '{print $2}')
              sed -i "/export IMAU_VSCODE_VERSION/c \export IMAU_VSCODE_VERSION=${fix_tag}" build.sh
              git config --global user.email "tserialt@gmail.com"
              git config --global user.name "serialt"
              git config --global --add safe.directory /github/workspace
              git add version.txt
              git add build.sh
              ADD_TAG=$t
              git commit -m "$APP $ADD_TAG (Github Actions Automatically Built in `date +"%Y-%m-%d %H:%M"`)"
              echo "ADD_TAG=${ADD_TAG}" >> $GITHUB_OUTPUT
              break
            else
              echo "::debug::[skip] $t"
            fi
          done
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: ${{ steps.get_tag.outputs.ADD_TAG != '' }}
        with:
          ssh: true
          branch: ${{ github.ref }}
      - name: Build && Push
        uses: docker/build-push-action@v2
        if: ${{ steps.get_tag.outputs.ADD_TAG != '' }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.get_tag.outputs.ADD_TAG }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest    
